local hrp = game:GetService("Players").LocalPlayer.Character.HumanoidRootPart
wait(0.25)
game:GetService("ReplicatedStorage").Events.Quest:FireServer("Anubis")
wait(0.5)
hrp.CFrame = CFrame.new(-1525, 62, -1989)
wait(0.5)
game:GetService("ReplicatedStorage").Events.Train:FireServer("EnduranceArea")
wait(1)
hrp.CFrame = CFrame.new(-1485, 62, -1909)
wait(0.5)
game:GetService("ReplicatedStorage").Events.Train:FireServer("Psychic")
wait(1)
hrp.CFrame = CFrame.new(-1609, 55, -1774)
wait(0.5)
game:GetService("ReplicatedStorage").Events.Train:FireServer("Strength")
wait(1)
game:GetService("ReplicatedStorage").Events.Quest:FireServer("Anubis")
hrp.CFrame = CFrame.new(-412, 71, -108)